name: Auto Author Assign

on: [pull_request, issues]

permissions:
  pull-requests: write
  issues: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Author Assign
        uses: toshimaru/auto-author-assign@v1.6.2
